<img src="logo.png">

In [1]:
%matplotlib inline
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns


In [3]:
datos = pd.read_csv("datos_procesamiento.csv")
datos.head()

col_inexistente1  col2      col3  col_outliers  col_outliers2  \
0              59.0  52.0  2.232832           -50       0.771666   
1              31.0  74.0  0.906147            -5       1.068558   
2              81.0  28.0  0.626750           -32       0.846396   
3              34.0  16.0  0.816738           -84       0.637381   
4              32.0  28.0  0.571131            65       4.540614   

  col_categorica col_ordinal  \
0          ratón    muy bien   
1       elefante     regular   
2          ratón     muy mal   
3           gato         mal   
4           gato        bien   

                                           col_texto  
0  Tenía en su casa una ama que pasaba de los cua...  
1  El resto della concluían sayo de velarte, calz...  
2  El resto della concluían sayo de velarte, calz...  
3  Una olla de algo más vaca que carnero, salpicó...  
4  Tenía en su casa una ama que pasaba de los cua...

In [4]:
datos.dtypes

col_inexistente1    float64
col2                float64
col3                float64
col_outliers          int64
col_outliers2       float64
col_categorica       object
col_ordinal          object
col_texto            object
dtype: object

In [5]:
datos.shape

(1000, 8)

# Variables Numéricas

**Imputación de datos**

In [6]:
from sklearn import preprocessing

In [7]:
datos.dtypes

col_inexistente1    float64
col2                float64
col3                float64
col_outliers          int64
col_outliers2       float64
col_categorica       object
col_ordinal          object
col_texto            object
dtype: object

In [19]:
var_numericas_df = datos.select_dtypes([int, float])
var_numericas_df["col_outliers"] = datos["col_outliers"]
var_numericas_df.columns

C:\Users\hp master\.conda\envs\scidata\lib\site-packages\ipykernel_launcher.py:2: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  


Index(['col_inexistente1', 'col2', 'col3', 'col_outliers2', 'col_outliers'], dtype='object')

In [20]:
var_numericas_df[var_numericas_df.isnull().any(axis=1)].shape

(96, 5)

In [21]:
var_numericas_df[var_numericas_df.isnull().any(axis=1)].head()

col_inexistente1  col2      col3  col_outliers2  col_outliers
9                NaN  53.0  2.270999       1.067230            62
10               NaN  99.0  1.394209       4.145716            98
16               NaN  50.0  0.437365      20.549474            59
17               NaN  73.0  0.324893       0.761684            98
23               NaN  85.0  3.664671       3.154153           -48

In [91]:
from sklearn.impute import SimpleImputer
imputador = SimpleImputer(missing_values=np.nan, copy=False, strategy="mean")

In [24]:
var_numericas_imputadas = imputador.fit_transform(var_numericas_df)

In [25]:
var_numericas_imputadas

array([[ 59.        ,  52.        ,   2.23283208,   0.77166646,
        -50.        ],
       [ 31.        ,  74.        ,   0.90614714,   1.06855838,
         -5.        ],
       [ 81.        ,  28.        ,   0.62675042,   0.84639576,
        -32.        ],
       ...,
       [ 19.        ,  53.        ,   0.73723413,   1.34525201,
         73.        ],
       [ 88.        ,  94.        ,   0.76008706,   1.3692463 ,
         68.        ],
       [ 94.        ,  56.        ,   1.2299403 ,   0.94395714,
         61.        ]])

In [26]:
var_numericas_imputadas.shape

(1000, 5)

In [27]:
var_numericas_imputadas_df = pd.DataFrame(var_numericas_imputadas,
                                                   index=var_numericas_df.index,
                                                   columns=var_numericas_df.columns)

var_numericas_imputadas_df.head(10)

col_inexistente1  col2       col3  col_outliers2  col_outliers
0         59.000000  52.0   2.232832       0.771666         -50.0
1         31.000000  74.0   0.906147       1.068558          -5.0
2         81.000000  28.0   0.626750       0.846396         -32.0
3         34.000000  16.0   0.816738       0.637381         -84.0
4         32.000000  28.0   0.571131       4.540614          65.0
5         81.000000   4.0   1.618844       0.812940          51.0
6         57.000000  31.0   0.167880       1.235137          78.0
7         34.000000  20.0  20.229813       1.283176          93.0
8         37.000000  96.0   2.407978       1.298613          54.0
9         48.382743  53.0   2.270999       1.067230          62.0

In [28]:
var_numericas_imputadas_df[var_numericas_imputadas_df.isnull().any(axis=1)].shape

(0, 5)

**Estandarización**

El proceso de Estandarización es un proceso requerido por una gran cantidad de modelos en Scikit-learn. El objetivo es obtener una variable con media 0 y desviación estándar 1.

In [29]:
var_numericas_df.columns

Index(['col_inexistente1', 'col2', 'col3', 'col_outliers2', 'col_outliers'], dtype='object')

In [30]:
var_numericas_df.mean()

col_inexistente1     48.382743
col2                 49.660000
col3                  1.466095
col_outliers2       131.193340
col_outliers          4.253000
dtype: float64

In [31]:
var_numericas_df.std()

col_inexistente1      27.987174
col2                  28.272668
col3                   1.732358
col_outliers2       3401.164776
col_outliers          78.145901
dtype: float64

Para ello el transformador mas sencillo en sklearn es [StandardScaler](http://scikit-learn.org/stable/modules/generated/sklearn.preprocessing.StandardScaler.html#sklearn.preprocessing.StandardScaler)

In [32]:
escalador = preprocessing.StandardScaler()
var_numericas_imputadas_escalado_standard = escalador.fit_transform(var_numericas_imputadas)

In [33]:
escalador.mean_

array([ 48.38274336,  49.66      ,   1.46609489, 131.19333968,
         4.253     ])

In [34]:
var_numericas_imputadas_escalado_standard.mean(axis=0)

array([-5.86197757e-17,  1.26121336e-16, -3.81916720e-17, -3.55271368e-18,
        3.55271368e-18])

In [35]:
var_numericas_imputadas_escalado_standard.std(axis=0)

array([1., 1., 1., 1., 1.])

In [36]:
var_numericas_imputadas_escalado_standard[0]

array([ 0.39921733,  0.08280686,  0.44281884, -0.03836537, -0.69460006])

Para aquellos casos en los que los datos tengan muchos valores extremos, es posible que estandarizar usando la media y la desviacion estandar no funcione bien en el modelo. Para esos casos es mejor usar unos estimadores mas robustos (menos sensibles a outliers) y emplear un [RobustScaler](http://scikit-learn.org/stable/modules/generated/sklearn.preprocessing.RobustScaler) que funciona substrayendo la mediana y escalando mediante el rango intercuartil (IQR).

In [37]:
escalador_robusto = preprocessing.RobustScaler()
var_numericas_imputadas_escalado_robusto = escalador_robusto.fit_transform(
                                                        var_numericas_imputadas)

In [38]:
var_numericas_imputadas_escalado_robusto.mean(axis=0)

array([-3.81916720e-17, -2.85106383e-02,  4.01958704e-01,  7.03130782e+01,
        3.04018692e-02])

In [39]:
var_numericas_imputadas_escalado_robusto.std(axis=0)

array([6.33218559e-01, 6.01245275e-01, 1.38651621e+00, 1.83690817e+03,
       7.29970260e-01])

**Escalado a un rango especifico**

Hay casos en los que en vez de estandardizar queremos escalar los datos a un rango (generalmente [-1,1] o [0,1]). Para ello podemos usar [MinMaxScaler](scikit-learn.org/stable/modules/generated/sklearn.preprocessing.MinMaxScaler) que hace escalado minmax (obviamente) o [MaxAbscaler](scikit-learn.org/stable/modules/generated/sklearn.preprocessing.MaxAbscaler) que simplemente divide cada valor de una variable por su valor máximo (y por tanto convierte el valor maximo a 1).

In [40]:
var_numericas_imputadas.min()

-100.0

In [41]:
var_numericas_imputadas.max()

107357.85777352

In [42]:
escalador_minmax = preprocessing.MinMaxScaler()
var_numericas_imputadas_escalado_minmax = escalador_minmax.fit_transform(var_numericas_imputadas)

In [43]:
var_numericas_imputadas_escalado_minmax.max()

1.0

In [44]:
var_numericas_imputadas_escalado_minmax.min()

0.0

In [45]:
escalador_maxabs = preprocessing.MaxAbsScaler()
var_numericas_imputadas_escalado_maxabs = escalador_maxabs.fit_transform(var_numericas_imputadas)

In [46]:
var_numericas_imputadas_escalado_maxabs.max()

1.0

In [47]:
var_numericas_imputadas_escalado_maxabs.min()

-0.1122334455667789

Hay casos en los que lo que se necesita es tener observaciones con norma unitaria (norma L2 o euclidiana). Para esos casos, podemos usar [Normalizer](http://scikit-learn.org/stable/modules/generated/sklearn.preprocessing.Normalizer.html#sklearn.preprocessing.Normalizer)

In [48]:
normalizador = preprocessing.Normalizer()
var_numericas_imputadas_normal = normalizador.fit_transform(var_numericas_imputadas)

Hay que tener en cuenta que el objetivo del Normalizer es normalizar casos, no variables (o sea que funciona por filas)

In [49]:
var_numericas_imputadas_normal[1,:]

array([ 0.38557802,  0.92041204,  0.01127066,  0.01329073, -0.06219   ])

In [50]:
np.linalg.norm(var_numericas_imputadas_normal[1,:])

1.0

<hr>

### Variables Categoricas

Los modelos están diseñados para trabajar con variables numéricas. Esto implica que para poder entrenar los modelos con variables categóricas tenemos que convertirlas a números. Este proceso se llama *codificación (encoding)*

In [54]:
datos = pd.read_csv("datos_procesamiento.csv")
datos.head()

col_inexistente1  col2      col3  col_outliers  col_outliers2  \
0              59.0  52.0  2.232832           -50       0.771666   
1              31.0  74.0  0.906147            -5       1.068558   
2              81.0  28.0  0.626750           -32       0.846396   
3              34.0  16.0  0.816738           -84       0.637381   
4              32.0  28.0  0.571131            65       4.540614   

  col_categorica col_ordinal  \
0          ratón    muy bien   
1       elefante     regular   
2          ratón     muy mal   
3           gato         mal   
4           gato        bien   

                                           col_texto  
0  Tenía en su casa una ama que pasaba de los cua...  
1  El resto della concluían sayo de velarte, calz...  
2  El resto della concluían sayo de velarte, calz...  
3  Una olla de algo más vaca que carnero, salpicó...  
4  Tenía en su casa una ama que pasaba de los cua...

In [55]:
var_categoricas = datos[['col_categorica', 'col_ordinal']]

In [56]:
var_categoricas.head()

col_categorica col_ordinal
0          ratón    muy bien
1       elefante     regular
2          ratón     muy mal
3           gato         mal
4           gato        bien

Hay muchas formas de codificar variables, la más sencilla es reemplazar los elementos de dichas variables por un número. Por ejemplo, si hacemos esto con la columna `col_ordinal`:

In [57]:
label_codificador = preprocessing.LabelEncoder()
label_codificador.fit(datos.col_ordinal) 

LabelEncoder()

In [58]:
label_codificador.classes_

array(['bien', 'mal', 'muy bien', 'muy mal', 'regular'], dtype=object)

In [59]:
label_codificador.transform(['muy bien', 'muy mal', 'muy bien', 'muy mal', 'bien'])

array([2, 3, 2, 3, 0], dtype=int64)

In [60]:
label_codificador.inverse_transform([0, 0, 1, 2])

array(['bien', 'bien', 'mal', 'muy bien'], dtype=object)

En el caso de variables ordinales esto tiene sentido ya que `muy_bien>bien>regular>mal>muy mal`. Sin embargo, esto indica a los modelos de scikit-learn por ejemplo que `mal + regular = bien`. Esto se puede usar en según que casos (hay modelos que no interpretan las variables numéricas así), o para codificar las variables objetivo.

Para variables categóricas (por ejemplo animales) no tiene sentido usar este tipo de encoding. 

In [61]:
label_codificador_categorico = preprocessing.LabelEncoder()
label_codificador_categorico.fit_transform(datos.col_categorica)[:10]

array([3, 0, 3, 1, 1, 2, 2, 2, 0, 0])

In [62]:
label_codificador_categorico.classes_

array(['elefante', 'gato', 'perro', 'ratón'], dtype=object)

Digamos que no tiene sentido decir que la media de `elefante` y `perro` no es `gato`

Para estos casos una técnica que se puede usar se llama `one-hot encoding`. Lo que significa es que creamos n columnas binarias, con el valor 0 por defecto salvo la columna referente a la observación.

Para esto podemos usar 
[OneHotEncoder](scikit-learn.org/stable/modules/generated/sklearn.preprocessing.OneHotEncoder.html)

In [63]:
oh_codificador = preprocessing.OneHotEncoder()

In [64]:
oh_codificador.fit(datos.col_categorica)

ValueError: Expected 2D array, got 1D array instead:
array=['ratón' 'elefante' 'ratón' 'gato' 'gato' 'perro' 'perro' 'perro'
 'elefante' 'elefante' 'perro' 'elefante' 'gato' 'ratón' 'gato' 'ratón'
 'elefante' 'ratón' 'ratón' 'elefante' 'ratón' 'ratón' 'ratón' 'gato'
 'gato' 'ratón' 'gato' 'elefante' 'gato' 'elefante' 'elefante' 'elefante'
 'elefante' 'ratón' 'elefante' 'gato' 'elefante' 'gato' 'gato' 'gato'
 'gato' 'ratón' 'elefante' 'gato' 'gato' 'perro' 'elefante' 'gato'
 'elefante' 'perro' 'ratón' 'perro' 'elefante' 'ratón' 'ratón' 'gato'
 'gato' 'elefante' 'ratón' 'perro' 'gato' 'gato' 'gato' 'gato' 'ratón'
 'elefante' 'elefante' 'perro' 'gato' 'ratón' 'perro' 'elefante' 'gato'
 'gato' 'ratón' 'ratón' 'elefante' 'perro' 'ratón' 'ratón' 'elefante'
 'gato' 'perro' 'ratón' 'gato' 'elefante' 'elefante' 'perro' 'perro'
 'perro' 'ratón' 'gato' 'ratón' 'gato' 'gato' 'elefante' 'gato' 'gato'
 'perro' 'perro' 'ratón' 'perro' 'gato' 'elefante' 'ratón' 'perro' 'gato'
 'gato' 'ratón' 'gato' 'perro' 'perro' 'perro' 'gato' 'perro' 'perro'
 'elefante' 'perro' 'ratón' 'gato' 'gato' 'gato' 'gato' 'ratón' 'ratón'
 'ratón' 'perro' 'elefante' 'elefante' 'perro' 'ratón' 'gato' 'elefante'
 'gato' 'ratón' 'ratón' 'elefante' 'gato' 'perro' 'ratón' 'gato'
 'elefante' 'elefante' 'elefante' 'elefante' 'perro' 'elefante' 'elefante'
 'gato' 'ratón' 'perro' 'perro' 'gato' 'perro' 'perro' 'elefante' 'gato'
 'perro' 'perro' 'perro' 'perro' 'gato' 'ratón' 'gato' 'gato' 'gato'
 'perro' 'ratón' 'ratón' 'elefante' 'ratón' 'ratón' 'elefante' 'elefante'
 'ratón' 'elefante' 'elefante' 'elefante' 'ratón' 'ratón' 'gato' 'perro'
 'elefante' 'elefante' 'gato' 'gato' 'perro' 'elefante' 'elefante'
 'elefante' 'ratón' 'perro' 'perro' 'gato' 'ratón' 'gato' 'perro' 'ratón'
 'elefante' 'ratón' 'ratón' 'gato' 'ratón' 'gato' 'ratón' 'elefante'
 'gato' 'gato' 'perro' 'elefante' 'perro' 'perro' 'gato' 'elefante'
 'elefante' 'elefante' 'gato' 'perro' 'gato' 'perro' 'elefante' 'elefante'
 'elefante' 'elefante' 'perro' 'gato' 'gato' 'elefante' 'ratón' 'perro'
 'perro' 'ratón' 'ratón' 'perro' 'perro' 'elefante' 'elefante' 'perro'
 'gato' 'perro' 'ratón' 'perro' 'ratón' 'gato' 'ratón' 'perro' 'elefante'
 'gato' 'gato' 'ratón' 'ratón' 'perro' 'gato' 'ratón' 'ratón' 'perro'
 'elefante' 'gato' 'ratón' 'perro' 'elefante' 'ratón' 'elefante' 'perro'
 'ratón' 'perro' 'perro' 'perro' 'ratón' 'ratón' 'ratón' 'perro'
 'elefante' 'perro' 'elefante' 'gato' 'elefante' 'elefante' 'elefante'
 'elefante' 'ratón' 'elefante' 'ratón' 'elefante' 'perro' 'ratón' 'gato'
 'elefante' 'perro' 'perro' 'ratón' 'perro' 'ratón' 'gato' 'gato' 'perro'
 'gato' 'ratón' 'perro' 'elefante' 'gato' 'perro' 'gato' 'elefante'
 'perro' 'ratón' 'gato' 'perro' 'elefante' 'elefante' 'gato' 'ratón'
 'gato' 'elefante' 'perro' 'perro' 'ratón' 'gato' 'ratón' 'gato' 'perro'
 'gato' 'perro' 'ratón' 'ratón' 'perro' 'ratón' 'gato' 'gato' 'ratón'
 'ratón' 'gato' 'perro' 'elefante' 'elefante' 'gato' 'ratón' 'gato'
 'ratón' 'gato' 'ratón' 'elefante' 'ratón' 'ratón' 'elefante' 'elefante'
 'gato' 'elefante' 'ratón' 'elefante' 'perro' 'elefante' 'elefante'
 'perro' 'gato' 'gato' 'elefante' 'perro' 'perro' 'perro' 'perro' 'gato'
 'perro' 'ratón' 'ratón' 'gato' 'elefante' 'gato' 'gato' 'perro' 'ratón'
 'perro' 'perro' 'elefante' 'ratón' 'ratón' 'gato' 'perro' 'perro'
 'elefante' 'gato' 'perro' 'gato' 'gato' 'ratón' 'ratón' 'gato' 'perro'
 'gato' 'ratón' 'perro' 'perro' 'ratón' 'gato' 'perro' 'perro' 'gato'
 'gato' 'perro' 'elefante' 'ratón' 'ratón' 'perro' 'elefante' 'elefante'
 'gato' 'ratón' 'elefante' 'perro' 'ratón' 'elefante' 'perro' 'perro'
 'gato' 'elefante' 'elefante' 'elefante' 'ratón' 'perro' 'gato' 'gato'
 'ratón' 'ratón' 'ratón' 'perro' 'elefante' 'gato' 'gato' 'gato' 'perro'
 'elefante' 'gato' 'elefante' 'elefante' 'elefante' 'ratón' 'gato' 'perro'
 'elefante' 'elefante' 'elefante' 'ratón' 'elefante' 'perro' 'ratón'
 'ratón' 'ratón' 'elefante' 'ratón' 'ratón' 'gato' 'ratón' 'perro' 'perro'
 'ratón' 'gato' 'elefante' 'perro' 'gato' 'gato' 'ratón' 'elefante'
 'ratón' 'ratón' 'ratón' 'gato' 'ratón' 'perro' 'elefante' 'ratón' 'ratón'
 'ratón' 'perro' 'ratón' 'ratón' 'perro' 'perro' 'gato' 'perro' 'ratón'
 'perro' 'elefante' 'ratón' 'elefante' 'gato' 'perro' 'gato' 'elefante'
 'ratón' 'perro' 'perro' 'gato' 'perro' 'gato' 'gato' 'perro' 'gato'
 'elefante' 'elefante' 'ratón' 'ratón' 'gato' 'gato' 'gato' 'perro'
 'elefante' 'gato' 'ratón' 'elefante' 'elefante' 'ratón' 'ratón' 'perro'
 'gato' 'gato' 'elefante' 'elefante' 'ratón' 'elefante' 'gato' 'ratón'
 'gato' 'gato' 'ratón' 'perro' 'ratón' 'elefante' 'ratón' 'elefante'
 'gato' 'gato' 'gato' 'gato' 'perro' 'gato' 'gato' 'ratón' 'perro'
 'elefante' 'gato' 'gato' 'ratón' 'perro' 'elefante' 'ratón' 'ratón'
 'elefante' 'ratón' 'perro' 'gato' 'perro' 'perro' 'perro' 'perro' 'gato'
 'ratón' 'gato' 'elefante' 'perro' 'gato' 'perro' 'ratón' 'ratón' 'perro'
 'elefante' 'elefante' 'elefante' 'perro' 'perro' 'ratón' 'perro' 'perro'
 'ratón' 'ratón' 'ratón' 'gato' 'perro' 'gato' 'gato' 'ratón' 'ratón'
 'gato' 'perro' 'gato' 'ratón' 'perro' 'perro' 'perro' 'ratón' 'ratón'
 'ratón' 'elefante' 'gato' 'gato' 'elefante' 'gato' 'gato' 'ratón' 'ratón'
 'ratón' 'perro' 'perro' 'elefante' 'elefante' 'elefante' 'elefante'
 'elefante' 'perro' 'ratón' 'ratón' 'ratón' 'gato' 'ratón' 'gato' 'gato'
 'elefante' 'elefante' 'elefante' 'perro' 'ratón' 'perro' 'perro' 'perro'
 'gato' 'ratón' 'elefante' 'perro' 'elefante' 'elefante' 'elefante'
 'elefante' 'elefante' 'perro' 'elefante' 'perro' 'ratón' 'elefante'
 'elefante' 'perro' 'gato' 'ratón' 'ratón' 'elefante' 'elefante' 'gato'
 'ratón' 'ratón' 'ratón' 'elefante' 'ratón' 'ratón' 'perro' 'perro'
 'perro' 'elefante' 'elefante' 'elefante' 'gato' 'ratón' 'elefante'
 'ratón' 'gato' 'perro' 'gato' 'elefante' 'gato' 'ratón' 'gato' 'gato'
 'elefante' 'gato' 'gato' 'elefante' 'perro' 'perro' 'gato' 'perro' 'gato'
 'ratón' 'gato' 'ratón' 'perro' 'perro' 'ratón' 'elefante' 'perro' 'perro'
 'gato' 'perro' 'gato' 'perro' 'elefante' 'ratón' 'elefante' 'perro'
 'perro' 'gato' 'perro' 'perro' 'gato' 'ratón' 'gato' 'gato' 'elefante'
 'gato' 'perro' 'gato' 'gato' 'perro' 'gato' 'ratón' 'ratón' 'perro'
 'gato' 'gato' 'elefante' 'ratón' 'perro' 'elefante' 'elefante' 'ratón'
 'ratón' 'perro' 'gato' 'perro' 'ratón' 'gato' 'gato' 'perro' 'perro'
 'perro' 'gato' 'perro' 'elefante' 'elefante' 'perro' 'perro' 'elefante'
 'ratón' 'gato' 'ratón' 'gato' 'elefante' 'elefante' 'perro' 'ratón'
 'gato' 'elefante' 'perro' 'perro' 'gato' 'gato' 'ratón' 'perro' 'perro'
 'ratón' 'perro' 'ratón' 'gato' 'perro' 'elefante' 'ratón' 'ratón' 'perro'
 'gato' 'perro' 'perro' 'perro' 'elefante' 'perro' 'gato' 'ratón' 'ratón'
 'perro' 'ratón' 'gato' 'gato' 'ratón' 'perro' 'ratón' 'ratón' 'perro'
 'elefante' 'gato' 'ratón' 'elefante' 'elefante' 'perro' 'gato' 'perro'
 'perro' 'gato' 'ratón' 'perro' 'ratón' 'gato' 'ratón' 'elefante'
 'elefante' 'perro' 'elefante' 'perro' 'gato' 'ratón' 'gato' 'perro'
 'elefante' 'elefante' 'ratón' 'elefante' 'ratón' 'elefante' 'elefante'
 'ratón' 'perro' 'perro' 'perro' 'elefante' 'ratón' 'gato' 'gato' 'gato'
 'perro' 'elefante' 'elefante' 'elefante' 'gato' 'elefante' 'perro' 'gato'
 'elefante' 'elefante' 'ratón' 'gato' 'gato' 'ratón' 'perro' 'elefante'
 'perro' 'perro' 'perro' 'elefante' 'perro' 'perro' 'elefante' 'perro'
 'elefante' 'gato' 'elefante' 'gato' 'gato' 'perro' 'gato' 'ratón'
 'elefante' 'perro' 'perro' 'perro' 'elefante' 'perro' 'ratón' 'gato'
 'elefante' 'gato' 'ratón' 'gato' 'gato' 'ratón' 'elefante' 'gato'
 'elefante' 'elefante' 'gato' 'perro' 'gato' 'elefante' 'perro' 'ratón'
 'elefante' 'elefante' 'elefante' 'elefante' 'perro' 'ratón' 'perro'
 'ratón' 'gato' 'elefante' 'ratón' 'ratón' 'perro' 'elefante' 'ratón'
 'ratón' 'perro' 'gato' 'elefante' 'ratón' 'ratón' 'gato' 'gato'
 'elefante' 'perro' 'elefante' 'perro' 'gato' 'perro' 'perro' 'perro'
 'perro' 'ratón' 'ratón' 'gato' 'perro' 'gato' 'elefante' 'perro' 'ratón'
 'perro' 'ratón' 'perro' 'gato' 'elefante' 'ratón' 'gato' 'perro' 'ratón'
 'perro' 'elefante' 'gato' 'ratón' 'perro' 'elefante' 'ratón' 'ratón'
 'ratón' 'perro' 'gato' 'gato' 'gato' 'perro' 'ratón' 'perro' 'ratón'
 'elefante' 'perro' 'perro' 'ratón' 'elefante' 'ratón' 'elefante' 'ratón'
 'gato' 'gato' 'gato' 'perro' 'elefante' 'gato' 'perro' 'gato' 'ratón'
 'ratón' 'gato' 'elefante' 'gato' 'elefante' 'elefante' 'gato' 'ratón'
 'ratón' 'ratón' 'gato' 'elefante' 'perro' 'perro' 'elefante' 'ratón'
 'perro' 'elefante' 'ratón' 'gato' 'perro' 'ratón' 'gato' 'gato' 'ratón'
 'ratón' 'gato' 'perro' 'perro' 'perro' 'elefante' 'gato' 'ratón' 'ratón'
 'elefante' 'ratón' 'elefante' 'elefante' 'elefante'].
Reshape your data either using array.reshape(-1, 1) if your data has a single feature or array.reshape(1, -1) if it contains a single sample.

Vemos que OneHotEncoder falla cuando se le pasan strings en vez de numeros. Por ello primero tenemos que convertir las variables categóricas a numéricas usando LabelEncoder.

In [65]:
categorias_codificadas = label_codificador_categorico.transform(datos.col_categorica)

In [66]:
categorias_codificadas

array([3, 0, 3, 1, 1, 2, 2, 2, 0, 0, 2, 0, 1, 3, 1, 3, 0, 3, 3, 0, 3, 3,
       3, 1, 1, 3, 1, 0, 1, 0, 0, 0, 0, 3, 0, 1, 0, 1, 1, 1, 1, 3, 0, 1,
       1, 2, 0, 1, 0, 2, 3, 2, 0, 3, 3, 1, 1, 0, 3, 2, 1, 1, 1, 1, 3, 0,
       0, 2, 1, 3, 2, 0, 1, 1, 3, 3, 0, 2, 3, 3, 0, 1, 2, 3, 1, 0, 0, 2,
       2, 2, 3, 1, 3, 1, 1, 0, 1, 1, 2, 2, 3, 2, 1, 0, 3, 2, 1, 1, 3, 1,
       2, 2, 2, 1, 2, 2, 0, 2, 3, 1, 1, 1, 1, 3, 3, 3, 2, 0, 0, 2, 3, 1,
       0, 1, 3, 3, 0, 1, 2, 3, 1, 0, 0, 0, 0, 2, 0, 0, 1, 3, 2, 2, 1, 2,
       2, 0, 1, 2, 2, 2, 2, 1, 3, 1, 1, 1, 2, 3, 3, 0, 3, 3, 0, 0, 3, 0,
       0, 0, 3, 3, 1, 2, 0, 0, 1, 1, 2, 0, 0, 0, 3, 2, 2, 1, 3, 1, 2, 3,
       0, 3, 3, 1, 3, 1, 3, 0, 1, 1, 2, 0, 2, 2, 1, 0, 0, 0, 1, 2, 1, 2,
       0, 0, 0, 0, 2, 1, 1, 0, 3, 2, 2, 3, 3, 2, 2, 0, 0, 2, 1, 2, 3, 2,
       3, 1, 3, 2, 0, 1, 1, 3, 3, 2, 1, 3, 3, 2, 0, 1, 3, 2, 0, 3, 0, 2,
       3, 2, 2, 2, 3, 3, 3, 2, 0, 2, 0, 1, 0, 0, 0, 0, 3, 0, 3, 0, 2, 3,
       1, 0, 2, 2, 3, 2, 3, 1, 1, 2, 1, 3, 2, 0, 1,

In [67]:
categorias_codificadas.shape

(1000,)

In [68]:
categorias_oh_codificadas = oh_codificador.fit_transform(categorias_codificadas.reshape(1000,1))
categorias_oh_codificadas

<1000x4 sparse matrix of type '<class 'numpy.float64'>'
	with 1000 stored elements in Compressed Sparse Row format>

Vemos que por defecto `OneHotEncoder` no devuelve un numpy array, sino una matriz `sparse`. La traducción sería "matriz escasa", y es una manera de representar matrices con muchos ceros (como es el caso de OneHot encoding) para consumir poca memoria.

Podemos convertir dichas matrices a arrays facilmente:

In [69]:
categorias_oh_codificadas.toarray()

array([[0., 0., 0., 1.],
       [1., 0., 0., 0.],
       [0., 0., 0., 1.],
       ...,
       [1., 0., 0., 0.],
       [1., 0., 0., 0.],
       [1., 0., 0., 0.]])

Vemos ahora la comparación en memoria de una matriz sparse versus su correspondiente np.array usando la función `sys.getsizeof` que devuelve el uso de memoria un objeto de python en bytes.

In [70]:
import sys
sys.getsizeof(categorias_oh_codificadas)

56

In [71]:
sys.getsizeof(categorias_oh_codificadas.toarray())

32112

Si queremos que el encoder devuelva arrays no tenemos más que pasarle el parametro `sparse=False`.

In [72]:
oh_codificador = preprocessing.OneHotEncoder(sparse=False)

categorias_oh_codificadas = oh_codificador.fit_transform(categorias_codificadas.reshape(1000,1))
categorias_oh_codificadas

array([[0., 0., 0., 1.],
       [1., 0., 0., 0.],
       [0., 0., 0., 1.],
       ...,
       [1., 0., 0., 0.],
       [1., 0., 0., 0.],
       [1., 0., 0., 0.]])

Pandas tiene la funcion auxiliar `get_dummies` que hace esto automáticamente de forma más fácil.

In [74]:
pd.get_dummies(datos.col_categorica).head()

elefante  gato  perro  ratón
0         0     0      0      1
1         1     0      0      0
2         0     0      0      1
3         0     1      0      0
4         0     1      0      0

### Texto

In [75]:
from sklearn import feature_extraction

In [76]:
datos.col_texto.values[:10]

array(['Tenía en su casa una ama que pasaba de los cuarenta, y una sobrina que no llegaba a los veinte, y un mozo de campo y plaza, que así ensillaba el rocín como tomaba la podadera.',
       'El resto della concluían sayo de velarte, calzas de velludo para las fiestas con sus pantuflos de lo mismo, los días de entre semana se honraba con su vellori de lo más fino.',
       'El resto della concluían sayo de velarte, calzas de velludo para las fiestas con sus pantuflos de lo mismo, los días de entre semana se honraba con su vellori de lo más fino.',
       'Una olla de algo más vaca que carnero, salpicón las más noches, duelos y quebrantos los sábados, lentejas los viernes, algún palomino de añadidura los domingos, consumían las tres partes de su hacienda.',
       'Tenía en su casa una ama que pasaba de los cuarenta, y una sobrina que no llegaba a los veinte, y un mozo de campo y plaza, que así ensillaba el rocín como tomaba la podadera.',
       'En un lugar de la Mancha, de cuyo nom

Para convertir texto en variables numéricas, podemos proceder de igual forma que con las variables categóricas, simplemente separando las palabras antes.

Para ello tenemos dos vectorizadores en scikit-learn, que convierten texto en vectores.


[CountVectorizer]() devuelve un vector con el valor 0 en todas las palabras que no existen en una frase y con el numero de ocurrencias de las palabras que si existen

Vamos a hacer un ejemplo para que se vea bien.

In [77]:
ejemplo_frases = ['los coches rojos',
          'los aviones son rojos',
          'los coches y los aviones son rojos',
          'los camiones rojos'
                 ]


vectorizador_count = feature_extraction.text.CountVectorizer()
X = vectorizador_count.fit_transform(ejemplo_frases)
X

<4x6 sparse matrix of type '<class 'numpy.int64'>'
	with 15 stored elements in Compressed Sparse Row format>

In [79]:
vectorizador_count.get_feature_names()

['aviones', 'camiones', 'coches', 'los', 'rojos', 'son']

In [80]:
pd.DataFrame(X.toarray(), columns=vectorizador_count.get_feature_names())

aviones  camiones  coches  los  rojos  son
0        0         0       1    1      1    0
1        1         0       0    1      1    1
2        1         0       1    2      1    1
3        0         1       0    1      1    0

El tomar simplemente el número de veces que aparece cada palabra tiene un problema, y es que da un mayor peso a aquellas palabras que aparecen muchas veces pero que no aportan ningun valor semántico (por ejemplo, `los`). Una manera más sofisticada de vectorizar un texto es en vez de usar el número de apariciones, usar TF-IDF. TF-IDF se traduce como Frecuencia de Texto - Frecuencia Inversa de Documento, y es una medida que asigna pesos a cada palabra en función de su frecuencia de aparición en todos los documents.

In [81]:
vectorizador_tfidf = feature_extraction.text.TfidfVectorizer()
X = vectorizador_tfidf.fit_transform(ejemplo_frases)
pd.DataFrame(X.toarray(), columns=vectorizador_tfidf.get_feature_names())

aviones  camiones    coches       los     rojos       son
0  0.000000  0.000000  0.730064  0.483222  0.483222  0.000000
1  0.589645  0.000000  0.000000  0.390280  0.390280  0.589645
2  0.438931  0.000000  0.438931  0.581047  0.290524  0.438931
3  0.000000  0.804612  0.000000  0.419880  0.419880  0.000000

In [86]:
vectorizador_tfidf = feature_extraction.text.TfidfVectorizer()
texto_vectorizado = vectorizador_tfidf.fit_transform(datos.col_texto)
texto_vectorizado

<1000x134 sparse matrix of type '<class 'numpy.float64'>'
	with 28295 stored elements in Compressed Sparse Row format>

In [87]:
texto_vectorizado = texto_vectorizado.toarray()
texto_vectorizado

array([[0.        , 0.        , 0.        , ..., 0.        , 0.        ,
        0.        ],
       [0.        , 0.        , 0.        , ..., 0.        , 0.        ,
        0.        ],
       [0.        , 0.        , 0.        , ..., 0.        , 0.        ,
        0.        ],
       ...,
       [0.        , 0.        , 0.        , ..., 0.        , 0.        ,
        0.        ],
       [0.19788701, 0.19788701, 0.        , ..., 0.        , 0.        ,
        0.19788701],
       [0.        , 0.        , 0.        , ..., 0.        , 0.        ,
        0.        ]])

In [84]:
label_codificador.classes_

array(['bien', 'mal', 'muy bien', 'muy mal', 'regular'], dtype=object)

**Poniendolo todo junto**

In [89]:
col_numericas =  ['col_inexistente1', 'col2', 'col3', 'col_outliers', 'col_outliers2']
col_categorica = ['col_categorica']
col_texto = ['col_texto']


#Variables numéricas
imputador = SimpleImputer(missing_values=np.nan, copy=False, strategy="mean")
escalador = preprocessing.StandardScaler()
var_numericas_imputadas_escalado_standard = escalador.fit_transform(
                                                imputador.fit_transform(datos[col_numericas])
                                            )
df_numerico_procesado = pd.DataFrame(var_numericas_imputadas_escalado_standard,
                                                   columns=col_numericas)


# Variable categorica
label_codificador_categorico = preprocessing.LabelEncoder()
categorias_codificadas = label_codificador_categorico.fit_transform(datos[col_categorica])
oh_codificador = preprocessing.OneHotEncoder(sparse=False)
categorias_oh_codificadas = oh_codificador.fit_transform(categorias_codificadas.reshape(1000,1))

df_categorico_procesado = pd.DataFrame(categorias_oh_codificadas, 
                                       columns=label_codificador_categorico.classes_)


# Texto
vectorizador_tfidf = feature_extraction.text.TfidfVectorizer()
texto_vectorizado = vectorizador_tfidf.fit_transform(datos.col_texto)
df_texto_procesado =  pd.DataFrame(texto_vectorizado.toarray(), columns=vectorizador_tfidf.get_feature_names())


datos_procesados = pd.concat([
    df_numerico_procesado,
    df_categorico_procesado,
    df_texto_procesado 
], axis=1)

# variable ordinal
label_codificador_ordinal = preprocessing.LabelEncoder()
datos_procesados['col_ordinal'] = label_codificador_ordinal.fit_transform(datos.col_ordinal) 

C:\Users\hp master\.conda\envs\scidata\lib\site-packages\sklearn\utils\validation.py:72: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  return f(**kwargs)


In [90]:
datos_procesados

col_inexistente1      col2      col3  col_outliers  col_outliers2  \
0            0.399217  0.082807  0.442819     -0.694600      -0.038365   
1           -0.653605  0.861333 -0.323390     -0.118466      -0.038278   
2            1.226435 -0.766494 -0.484752     -0.464146      -0.038343   
3           -0.540803 -1.191145 -0.375028     -1.129901      -0.038405   
4           -0.616004 -0.766494 -0.516874      0.777743      -0.037257   
..                ...       ...       ...           ...            ...   
995          1.376838  0.365907  0.492254      0.611304      -0.038492   
996         -0.352799 -1.615795  0.131503      0.700925      -0.037878   
997         -1.104815  0.118194 -0.420944      0.880166      -0.038197   
998          1.489641  1.569084 -0.407745      0.816152      -0.038190   
999          1.715245  0.224357 -0.136388      0.726531      -0.038315   

     elefante  gato  perro  ratón  acordarme  ...      vaca    veinte  \
0         0.0   0.0    0.0    1.0   0.000000  ...  0.000000  0.204745   
1         1.0   0.0    0.0    0.0   0.000000  ...  0.000000  0.000000   
2         0.0   0.0    0.0    1.0   0.000000  ...  0.000000  0.000000   
3         0.0   1.0    0.0    0.0   0.000000  ...  0.194272  0.000000   
4         0.0   1.0    0.0    0.0   0.000000  ...  0.000000  0.204745   
..        ...   ...    ...    ...        ...  ...       ...       ...   
995       1.0   0.0    0.0    0.0   0.000000  ...  0.000000  0.000000   
996       0.0   0.0    0.0    1.0   0.000000  ...  0.000000  0.204745   
997       1.0   0.0    0.0    0.0   0.000000  ...  0.000000  0.000000   
998       1.0   0.0    0.0    0.0   0.197887  ...  0.000000  0.000000   
999       1.0   0.0    0.0    0.0   0.000000  ...  0.000000  0.204745   

      velarte   vellori   velludo  verdad  verosímiles   viernes     vivía  \
0    0.000000  0.000000  0.000000     0.0          0.0  0.000000  0.000000   
1    0.181842  0.181842  0.181842     0.0          0.0  0.000000  0.000000   
2    0.181842  0.181842  0.181842     0.0          0.0  0.000000  0.000000   
3    0.000000  0.000000  0.000000     0.0          0.0  0.194272  0.000000   
4    0.000000  0.000000  0.000000     0.0          0.0  0.000000  0.000000   
..        ...       ...       ...     ...          ...       ...       ...   
995  0.000000  0.000000  0.000000     0.0          0.0  0.000000  0.000000   
996  0.000000  0.000000  0.000000     0.0          0.0  0.000000  0.000000   
997  0.181842  0.181842  0.181842     0.0          0.0  0.000000  0.000000   
998  0.000000  0.000000  0.000000     0.0          0.0  0.000000  0.197887   
999  0.000000  0.000000  0.000000     0.0          0.0  0.000000  0.000000   

     col_ordinal  
0              2  
1              4  
2              3  
3              1  
4              0  
..           ...  
995            3  
996            2  
997            4  
998            0  
999            4  

[1000 rows x 144 columns]